### ISSUE TITLE
does not work with rails 3.1

### ISSUE THREAD

**Issue by gabrielbaez** [fajrif/has_mailbox#3]
undefined method `paginate' for []:ActiveRecord::Relation

Started GET "/mailboxes" for 192.168.1.252 at Fri Oct 21 20:43:53 -0500 2011
  Processing by MailboxesController#index as HTML
  User Load (1.2ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1
  HasMailbox::Models::Message Load (0.8ms)  SELECT "messages".\* FROM "messages" WHERE "messages"."received_messageable_id" = 1 AND "messages"."received_messageable_type" = 'User' AND "messages"."deleted" = 'f' ORDER BY created_at desc
Completed 500 Internal Server Error in 35ms

NoMethodError (undefined method `paginate' for []:ActiveRecord::Relation):

Rendered /var/lib/gems/1.8/gems/actionpack-3.1.0/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
Rendered /var/lib/gems/1.8/gems/actionpack-3.1.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
Rendered /var/lib/gems/1.8/gems/actionpack-3.1.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (5.0ms)
